### ISSUE TITLE
Can't git push

### ISSUE THREAD

**Issue by shanecarr1** [githubschool/conflict-practice-shanecarr1#4]
Hi @crichID . I'm trying to do merge conflict on the 3rd pull request via command line. I followed the video and when I attempt to git push it asks for my GitHub credentials as opposed to my SSH (which I've been using all along). After copy and pasting, and writing out the password up to a dozen times, I think it is not working because of the 2FA. How can I switch it back over to SSH?

Any ideas?

Thanks a million

**Comment by crichID** [comment]
Hi @shanecarr1 :wave: in order to switch back to SSH, you simply need to change the remote URL. Enter the following on the command line: `git remote set-url origin git@github.com:githubschool/conflict-practice-shanecarr1.git` and you should be able to push. We will talk about remotes today during class :smile:

**Comment by shanecarr1** [comment]
Yesss!!! That worked, thank you! 💖
